version:2
jobs:
  build:
	  docker:
		  - image: circleci/node:6.9

		working_directory: ~/repo

		steps:
		  - setup_remote_docker:
			  version: 17.09.0-ce
			- checkout
			- run: docker build -t platzi .

			- restore_cache:
			  keys:
				  - v1-dependencies-{{ checksum "package.json" }}
					- v1-dependencies-
			- run: yarn install
			- save_cache:
			  paths:
				  - node_modules
				key: v1-dependencies-{{ checksum "package.json" }}
			- run: yarn test

